# Generated by Django 5.2.15 on 2026-06-24 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form137Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('is_printed', models.BooleanField(default=False)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form137_records', to='academics.gradelevel')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form137_records', to='academics.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form137_records', to='students.student')),
            ],
            options={
                'ordering': ['-date_generated'],
                'unique_together': {('student', 'school_year', 'grade_level')},
            },
        ),
    ]
