# Generated by Django 5.1.15 on 2026-10-09 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_adviser_from_section(apps, schema_editor):
    """Assign each student's section adviser so existing records stay complete."""
    Student = apps.get_model('students', 'Student')
    for student in Student.objects.filter(
        section__isnull=False,
        section__adviser__isnull=False,
        adviser__isnull=True,
    ).select_related('section'):
        student.adviser = student.section.adviser
        student.save(update_fields=['adviser'])


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='adviser',
            field=models.ForeignKey(blank=True, help_text='Teacher assigned to this student. Required when enrolling a new student.', limit_choices_to={'is_active': True, 'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_students', to=settings.AUTH_USER_MODEL, verbose_name='Adviser (Teacher)'),
        ),
        migrations.RunPython(backfill_adviser_from_section, migrations.RunPython.noop),
    ]
