# Generated by Django 5.2.15 on 2026-06-24 06:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradesubmission',
            unique_together={('teacher', 'subject', 'section', 'school_year', 'grading_period')},
        ),
    ]
