# Generated by Django 5.1.15 on 2026-07-04 23:22

from django.db import migrations


def migrate_locked_to_validated(apps, schema_editor):
    Grade = apps.get_model('grades', 'Grade')
    Grade.objects.filter(status='locked').update(status='validated')


def reverse_migrate(apps, schema_editor):
    Grade = apps.get_model('grades', 'Grade')
    Grade.objects.filter(status='validated').update(status='locked')


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0002_alter_gradesubmission_unique_together"),
    ]

    operations = [
        migrations.RunPython(migrate_locked_to_validated, reverse_migrate),
    ]
