# Generated by Django 5.1.15 on 2026-10-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_migrate_locked_to_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradesubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Under Review'), ('approved', 'Approved'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='gradevalidation',
            name='status',
            field=models.CharField(choices=[('pending', 'Under Review'), ('approved', 'Approved'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
