# Generated by Django 5.1.15 on 2026-10-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_reconcile_grade_status_with_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='assessment_highest',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
        migrations.AddField(
            model_name='grade',
            name='performance_task_highest',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
        migrations.AddField(
            model_name='grade',
            name='written_work_highest',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
        migrations.AlterField(
            model_name='grade',
            name='assessment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='grade',
            name='performance_task',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='grade',
            name='written_work',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
