# Generated by Django 5.1.15 on 2026-10-06 14:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0007_grade_assessment_1_grade_assessment_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="assessment_weight",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("50"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="performance_task_weight",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("20"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="written_work_weight",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("20"), max_digits=5
            ),
        ),
    ]
