# Generated by Django 5.1.15 on 2026-10-06 14:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0009_backfill_legacy_grade_weights"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="written_work_4",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="written_work_5",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="assessment_weight",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("30"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="performance_task_weight",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("50"), max_digits=5
            ),
        ),
    ]
