# Generated by Django 5.1.15 on 2026-10-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0011_grade_assessment_1_highest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="assessment_1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="grade",
            name="assessment_2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="grade",
            name="assessment_3",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="grade",
            name="performance_task_1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="grade",
            name="performance_task_2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="grade",
            name="performance_task_3",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="grade",
            name="written_work_1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="grade",
            name="written_work_2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="grade",
            name="written_work_3",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="grade",
            name="written_work_4",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="grade",
            name="written_work_5",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
