# Generated by Django 5.1.15 on 2026-09-22 08:13

from django.db import migrations, models


def reassign_principals_to_registrar(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='principal').update(role='registrar')


def revert_principals(apps, schema_editor):
    # Historical principal identities cannot be recovered; no-op on rollback.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(reassign_principals_to_registrar, revert_principals),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'System Administrator'), ('registrar', 'Registrar'), ('teacher', 'Teacher'), ('student', 'Student/Parent')], default='teacher', max_length=20),
        ),
    ]
