# Generated by Django 5.1.15 on 2026-09-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_retire_principal_demo_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Login'), ('logout', 'Logout'), ('grade_encode', 'Grade Encoded'), ('grade_update', 'Grade Updated'), ('grade_submit', 'Grade Submitted'), ('grade_validate', 'Grade Validated'), ('grade_return', 'Grade Returned'), ('form137_generate', 'Form 137 Generated'), ('form137_print', 'Form 137 Printed')], max_length=20),
        ),
    ]
