# Generated by Django 5.1.15 on 2026-07-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradingperiod",
            name="is_submissions_open",
            field=models.BooleanField(
                default=False, verbose_name="Open for Grade Submissions"
            ),
        ),
    ]
