# Generated by Django 5.1.15 on 2026-10-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_gradingperiod_is_submissions_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingperiod',
            name='end_month',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Last calendar month this quarter covers (e.g. August).', null=True, verbose_name='End Month'),
        ),
        migrations.AddField(
            model_name='gradingperiod',
            name='start_month',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='First calendar month this quarter covers (e.g. June).', null=True, verbose_name='Start Month'),
        ),
    ]
